### ISSUE TITLE
How to adapt the gripper model

### ISSUE THREAD

**Issue by clemense** [maximeadjigble/grasplocomo#1]
What's the easiest way to change the gripper model?  (i.e. changing the dimensions of the three boxes that represent the gripper, and the frame of reference)

**Comment by maximeadjigble** [comment]
Hi Clemens, 
You can do that by changing the values of the variables fingerxyz (Fingers dimensions), gripperxyz (gripper base dimensions) and openingMax (Maximum opening of the gripper) in the file "include/dxGripperModel.h" (line 743, 744, 738). The figure @687-713 illustrates what those values are. 

PS: currently the collision detection on the gripper base is very simple. It uses the largest sphere fitting in the gripper shape as the collision model, so if your gripper is not cubic, you may get grasps that collides with the objects. One thing that you can do is to additionally check for collusion using the proper bounding box of your gripper once you get the grasps.
