### ISSUE TITLE
Implementation on Linux

### ISSUE THREAD

**Issue by Olalm** [maximeadjigble/grasplocomo#2]
Any suggestions on how to implement project in Linux? Struggling because Visual Studio Community is not compatible with Linux.

**Comment by maximeadjigble** [comment]
Could you please send a print screen of the error message and also provide your computer configuration and I will have a look

**Comment by Olalm** [comment]
I’m configuring and generating project using the Unix Makefiles Generator. This is the problem list. 
![image](https://user-images.githubusercontent.com/98749834/160353128-5a6d8d05-cc4e-4db8-857d-fb01eee8ad08.png)
However, when I use Microsoft and Visual Studio Generator it works with no issues.
Linux version:
![image](https://user-images.githubusercontent.com/98749834/160353258-774d4857-5668-4ea8-9514-f96b11e80be6.png)

**Comment by Olalm** [comment]
The dxGraspLoCoMo.h file is available so I do not know why this error shows.
![image](https://user-images.githubusercontent.com/98749834/160596462-c0cea69d-c103-472e-ae17-027e84832ce1.png)

When I build the solution, this is the final output:
![image](https://user-images.githubusercontent.com/98749834/160596540-7332fc82-f628-4875-bd84-8f9ec01219c8.png)

This is the CMake configuration I am using:
![image](https://user-images.githubusercontent.com/98749834/160596596-d14158ea-6186-40d2-b824-84a782ca9c57.png)

Linux distribution:
![image](https://user-images.githubusercontent.com/98749834/160611787-977deee8-bbd3-4b07-b29c-65928c4cb2ba.png)

**Comment by kristianmk** [comment]
See the following pull request https://github.com/maximeadjigble/grasplocomo/pull/3

**Comment by maximeadjigble** [comment]
Hi, ok i will have a look at it this week and update the code so that it can also be compiled on ubuntu

**Comment by maximeadjigble** [comment]
Hi @Olalm , Kristian has done a great job and has updated the code for Ubuntu. You can find the updated version here.
https://github.com/kristianmk/grasplocomo

To compile, you need to:
- Clone the repository
- Open a terminal and change directory: cd grasplocomo
Run
- git submodule init
- git submodule update
Once the modules are installed, run
- cmake .
- make

And you will have in the /lib folder the built library libdxGraspLoCoMo.a, and the file at /Grasp/dxTestGraspLoCoMo that you can execute for a demonstration of the algorithm. You will need to move the folder /Clouds a level up ../grasplocomo for the point clouds to be found or change the location of the folder in /grasp/test/dxGraspLoCoMoTest.cpp (line 96).

I'll merge both branches later this week, but in the meantime this will solve your problem
