### ISSUE TITLE
Implementing on robot with 5 DOF

### ISSUE THREAD

**Issue by Olalm** [maximeadjigble/grasplocomo#6]
Hi! I am using a robot with 5 degrees of freedom. The robot has roll and pitch, but lacks yaw. This gives some issues when using the transformation matrix outputted from LoCoMo. The robot I am using is a VX300 from trossen robotics, and there are no functions there that inputs a transformation matrix and gives out a valid pose. This is only possible for 6 DOF robot. Do you have any advice on how to work around this problem? Is it possible to modify the script so that it is compatible with a 5 DOF robot?

**Comment by maximeadjigble** [comment]
Hi,
The code does not take in account the kinematics of the robot. What we usually do is that we generate the grasps and check for IK afterward. One thing that you may want to investigate is to generate more grasps and try to find an approximate IK solver that gets you as close as possible to the desired grasp, use that pose and hopefully the grasp will be successful. At the moment, there is no easy way to integrate the kinematics of the gripper in the grasp generation process.

In Grasp/include/dxGripperModel.h, you can increase the variable NrotSampled, to increase the number of grasps generated per features. At the moment, for each feature 10 grasps are generated

**Comment by Olalm** [comment]
Ok! Thank you for the reply!
